apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - args:
    - echo Hi! welcome to {{ .Values.country }}, my name is {{ .Values.person }}
    command:
    - /bin/sh
    - -c
    image: alpine
    name: alpine-crt
